# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47d967e67cd299db9cf3bb335babcf2275f71759e828ff8d83d98d9beb42a5fa5286c6289d6b16d41068c3ed8513ef582f7353e26f12f390001692caef2039de

test:
  secret_key_base: a4e0f3240ec1ba74f1979ae12d522b23450fee7cf286e91b72af4d6d23f6d93ff5ffd01db96c2f6ad1c606a88f4120513c4bb8fce5d5868cb9210b5dacc89ffb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
